apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: cronjob
spec:
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: cronjob
        resources: {}
      restartPolicy: Never
status: {}
