apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: cronjob
spec:
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - echo hello
        image: busybox
        name: cronjob
        resources: {}
      restartPolicy: Never
status: {}
