apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend1
  name: backend1
spec:
  containers:
  - image: nginx
    name: backend1
    envFrom:
      - configMapRef:
          name: db-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
