apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secured
  name: secured
spec:
  # modify replicas according to your case
  replicas: 3
  securityContext:
    fsGroup: 3000
  containers:
  - image: nginx
    name: secure
    volumeMounts:
    - name: data-vol
      mountPath: /data/app
  volumes:
    - name: data-vol
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
